### ISSUE TITLE
ch5 kubelet-api-admin-template missing

### ISSUE THREAD

**Issue by tupacalypse187** [Policy-as-Code-Book/first-edition#1]
When running `./up_styra.sh` from ch5, there is no `kubelet-api-admin-template.yaml` in the `ch5-opa-k8s/install/templates` directory.

Was this file not meant to be included for configuring DAS or is there a different way to generate?

Thank you.

```
$ ./up-styra.sh
cat: templates/kubelet-api-admin-template.yaml: No such file or directory
error: no objects passed to apply
Error 1 occurred on 21
```

**Comment by jimmyraywv** [comment]
Added file and updated script.

**Comment by jimmyraywv** [comment]
Aged
